import time

def BrazilFlag():
    print("[.............]")
    time.sleep(0.1)
    print("[####.........]")
    time.sleep(0.1)
    print("[###########..]")
    time.sleep(0.1)
    print("[#############]")
    time.sleep(0.1)
    print("                            .''")
    time.sleep(0.1)
    print("                         .,lO00kl,.")
    time.sleep(0.1)
    print("                      .;ooc,'..',col,.")
    time.sleep(0.1)
    print("                   .;dk;.          .:ko,.")
    time.sleep(0.1)
    print("                .;d00o.              .x0Od;.")
    time.sleep(0.1)
    print("             .:x00000dlloooddllclc,.. .O0000d;.")
    time.sleep(0.1)
    print("           .l0000000klc;;;,;:::coodk0000000000Oc.")
    time.sleep(0.1)
    print("             .:x0000k.. .. .  .     .'l00000d:.")
    time.sleep(0.1)
    print("                .:d00d. . .. ... ....'x0Od;.")
    time.sleep(0.1)
    print("                   .;dk;.  .      .':ko;.")
    time.sleep(0.1)
    print("                      .;ooc,'..',col,.")
    time.sleep(0.1)
    print("                         .,lO00kl,.")
    time.sleep(0.1)
    print("                            .''")
    time.sleep(0.1)
    time.sleep(0.1)
    print("#")
    time.sleep(0.1)
    print("#1")
    time.sleep(0.1)
    print("#11")
    time.sleep(0.1)
    print("#110")
    time.sleep(0.1)
    print("#1101")
    time.sleep(0.1)
    print("bandeira")
    time.sleep(0.1)
    print("bandeira do")
    time.sleep(0.1)
    print("bandeira do BRASIL")
    time.sleep(0.1)
    print("bandeira do BRASIL finalizada")
    time.sleep(0.1)
    print("bandeira do BRASIL finalizada :)")