def OP():
    print("")
    print(" ---------------------------------------")
    print("|                OPÇÕES                 |")
    print(" --------------------------------------- ")
    print("|    FUNÇÃO             |  COMANDO      |")
    print(" --------------------------------------- ")
    print("|  PESQUISAR POR ESTADO | estado        |")
    print("|  PESQUISAR POR DDD    | ddd           |")
    print("|  BANDEIRA DO BRASIL   | bandeira      |")
    print("|  SAIR DO APP          | sair          |")
    print("|  LISTAS               | lista         |")
    print("|  AJUDA                | --help        |")
    print(" --------------------------------------- ")